Repository Architects8080/frontend, pull requests merged in 2021-10, with the labels that each got.

#28 FEAT : #27 add otp login
  src/App.tsx
  src/views/auth/otp/otp.tsx
Labels: 💻 feature, Frontend

#31 FEAT : #30 add setting otp, avatar
  src/components/modal/otp/otpModal.tsx
  src/views/setting/setting.tsx
Labels: 💻 feature, Frontend

#35 Feat/#34/channel 입장, 퇴장 관련 화면 구현
  src/components/modal/chatroom/create/chatroomCreateModal.tsx
  src/components/modal/chatroom/join/enterPasswordModal.tsx
  src/views/chatroom/chatroom.tsx
  src/views/main/chatroomItem/item.tsx
Labels: 💻 feature, Frontend

#49 FEAT : #48 register error handle using snackbar
  src/views/auth/register/register.tsx
Labels: 💻 feature, Frontend

#54 FEAT : #50 blocklist & item
  src/App.tsx
  src/components/sideBar/userTemplate/user.scss
  src/views/blocklist/blockItem/blockItem.scss
  src/views/blocklist/blockItem/blockItem.tsx
  src/views/blocklist/blocklist.scss
  src/views/blocklist/blocklist.tsx
Labels: 💻 feature, Frontend

#62 FIX : #61 game scroll when focusing canvas
  src/components/dropdown/dropdownItem/inviteGame.tsx
  src/views/chatroom/chatroom.tsx
  src/views/game/pong/pong.tsx
Labels: bug, Frontend

#58 FEAT : #23 default withCredentials setting
  src/index.tsx
Labels: 💻 feature, Frontend

#69 FEAT : #68 register result setting
  src/views/auth/register/register.tsx
Labels: 💻 feature

#71 FEAT : #70 blockList
  src/components/sideBar/sideBar.tsx
  src/views/blocklist/blockItem/blockItem.tsx
  src/views/blocklist/blocklist.tsx
Labels: 💻 feature, Frontend

#74 FIX : #73 otp modal not showing problem
  src/components/modal/otp/otpModal.scss
  src/components/modal/otp/otpModal.tsx
  src/views/setting/setting.tsx
Labels: bug, Frontend

#76 Feat/#75/achievement
  src/components/achievement/achievement.tsx
  src/views/profile/profile.tsx
Labels: 💻 feature, Frontend
